spring:
  aop:
    proxyTargetClass: true
  application:
    name: uaa-service
  thymeleaf:
    cache: false

server:
  port: 8081
  servlet:
    context-path: /uaa
  use-forward-headers: false

eureka:
  instance:
      hostname: localhost
      non-secure-port: 8761
  client:
    should-enforce-registration-at-init: true
    service-url:  
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka/
       

logging:
  level:
    org.springframework.cloud: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

